# 环境变量（debug|development|prodction)

# env: 'debug'
# env: 'development'
env: 'production'

# 管理界面URL
manageURL:
  'https://manage.helibin.com'

# 数据库配置
dbServer:
  mysql:
    host              : '127.0.0.1'
    port              : '3306'
    username          : '<username>'
    password          : null
    database          : '<database>'
    connectionLimit   : 5        # 连接池大小
    acquireTimeout    : 30000    # 超时时间
    multipleStatements: true     # 允许多条SQL语句
    timezone          : '+08: 00' # 时区

  redis:
    host    : '127.0.0.1'
    password: null
    port    : 6379
    db      : 0

  socketIO:
    host    : '127.0.0.1'
    password: null
    port    : 6379

# 站点服务
webServer:
  host: '0.0.0.0'
  port: 5080

  pageSize: 20
  pageSizeMax: 1000

  xAuthMaxAge: 7200           # 用户认证通用过期时间，秒
  xAuthHeader: 'x-auth-token' # HTTP Header中用户令牌字段名，`false`为禁用
  xAuthQuery : 'xAuthToken'   # QueryString中用户令牌字段名，`false`为禁用
  xAuthCookie: 'xAuthToken'   # Cookie中用户令牌字段名，`false`为禁用

  captchaMaxAge: # 验证码过期时间，秒
    svg: 300
  smsCodeMaxAge: # 短信验证码过期时间，秒
    aly: 900
  smsCodRetryTimeout: # 短信验证码重试时间间隔，秒
    aly: 60
  mailCodeMaxAge: # 邮件验证码过期时间，秒
    aly: 900
  mailCodRetryTimeout: # 邮件验证码重试时间间隔，秒
    aly: 60

  secret: 'secret-binapi-oYfKQsdb8NALAXGR' # 通用密钥：用于Cookie签名、密码加盐等

  defaultLocale: 'zh-CN'

  skipCaptcha: false

# API服务
apiServer:
  prefix       : '/v1'
  corsWhiteList: '*'
  ipWhiteList  : '*'

  logLevel: 'ERROR' # 日志等级（ALL, TRACE, DEBUG, INFO, WARN, ERROR, FATAL, MARK, OFF）
  sentryDSN: null

# socketIO
socketServer:
  prefix : '/s1'

# 公共API
openAPI:
  taobao:
    ip: 'http://ip.taobao.com/service/getIpInfo2.php?ip='

# log4js日志等级列表
logLevels:
  all: 'white'
  trace: 'blue'
  debug: 'cyan'
  info: 'green'
  warn: 'yellow'
  error: 'red'
  fatal: 'magenta'

# hbs模板
hbs:
  partials:
    'header.base': 'layout/header.base'
    'header'     : 'layout/header'
    'footer.base': 'layout/footer.base'
    'footer'     : 'layout/footer'

# AES加密
AES:
  key: 'jKDUqUyRezqNyQaY5faKYsZHLADHmD9e'
  iv: 'dvjMpXLMb8592RZr'

# 阿里云SDK
alySDK:
  accessKeyId: null
  accessKeySecret: null
  dayu:
    accessKeyId: null
    accessKeySecret: null
    endpoint: 'http://dysmsapi.aliyuncs.com'
    apiVersion: '2015-12-16'
    signName: null
    template:
      default: null
  oss:
    accessKeyId: null
    accessKeySecret: null
    endpoint: 'https://oss-cn-shenzhen.aliyuncs.com'
    apiVersion: '2013-10-15'
    bucketName: null
    cacheExpire: 900 # 缓存时间，秒
  yqBridge:
    accessKeyId    : null
    accessKeySecret: null
    endpoint       : 'https://yq-bridge.aliyuncs.com'         # 外网
    apiVersion     : '2017-08-10'
  aas:
    accessKeyId    : null
    accessKeySecret: null
    endpoint       : 'https://aas.aliyuncs.com'         # 外网
    apiVersion     : '2015-07-01'
    sessionTicket  : 'login_aliyunid_ticket'
    type:
      - 'biz'
      - 'master'
      - 'ram'
      - 'token'

# 阿里云服务
alyServer:
  accessKeyId: null
  accessKeySecret: null
  sms:
    accessKeyId: null
    accessKeySecret: null
    signName: null
    template:
      default: null

# NodeMailer
nodeMailer:
  host: 'smtp.mxhichina.com'
  port: 465
  secure: true
  user: null
  password: null
  sender: null
  name: null

# 赛邮
subMailServer:
  sms:
    accessKeyId: null
    accessKeySecret: null
    signName: null
    template:
      default: null
  mail:
    accessKeyId: null
    accessKeySecret: null

# 微信服务
wxServer:
  secret: 'weixin-secret'
