# 环境变量（debug|development|prodction)

# env: 'debug'
# env: 'development'
env: 'production'

# 管理界面URL
manageURL:
  'https://manage.helibin.com'

# 数据库配置
dbServer:
  mysql:
    host              : '127.0.0.1'
    port              : '3306'
    username          : '<username>'
    password          : null
    database          : '<database>'
    connectionLimit   : 5        # 连接池大小
    acquireTimeout    : 30000    # 超时时间
    multipleStatements: true     # 允许多条SQL语句
    timezone          : '+08: 00' # 时区

  redis:
    host    : '127.0.0.1'
    port    : 6379
    db      : 0
    password: null

# 站点服务
webServer:
  host: '0.0.0.0'
  port: 5080

  pageSize: 20
  pageSizeMax: 1000

  xAuthMaxAge: 7200           # 用户认证通用过期时间，秒
  xAuthHeader: 'x-auth-token' # HTTP Header中用户令牌字段名，`false`为禁用
  xAuthQuery : 'xAuthToken'   # QueryString中用户令牌字段名，`false`为禁用
  xAuthCookie: 'xAuthToken'   # Cookie中用户令牌字段名，`false`为禁用

  captchaMaxAge: # 验证码过期时间，秒
    svg: 300

  secret: 'secret-binapi-oYfKQsdb8NALAXGR' # 通用密钥：用于Cookie签名、密码加盐等

  defaultLocale: 'zh-CN'

# API服务
apiServer:
  prefix       : '/v1'
  corsWhiteList: '*'
  ipWhiteList  : '*'

  logLevel: 'ERROR' # 日志等级（ALL, TRACE, DEBUG, INFO, WARN, ERROR, FATAL, MARK, OFF）
  sentryDSN: ''

# 公共API
openAPI:
  taobao:
    ip: 'http://ip.taobao.com/service/getIpInfo2.php?ip='

# log4js日志等级列表
logLevels:
  all: 'cyan'
  trace: 'blue'
  debug: 'white'
  info: 'white'
  warn: 'yellow'
  error: 'red'
  fatal: 'magenta'

# hbs模板
hbs:
  partials:
    'header.base': 'layout/header.base'
    'header'     : 'layout/header'
    'footer.base': 'layout/footer.base'
    'footer'     : 'layout/footer'

# AES加密
AES:
  key: 'jKDUqUyRezqNyQaY5faKYsZHLADHmD9e'
  iv: 'dvjMpXLMb8592RZr'
