# 环境变量（debug|development|prodction)

# env: 'debug'
# env: 'development'
env: 'production'

# 管理界面URL
adminURL:
  'https://admin.helibin.com'

# 数据库配置
dbServer:
  mysql:
    host              : '127.0.0.1'
    port              : '3306'
    username          : '<username>'
    password          : null
    database          : '<database>'
    connectionLimit   : 5        # 连接池大小
    acquireTimeout    : 30000    # 超时时间
    multipleStatements: true     # 允许多条SQL语句
    timezone          : '+08: 00' # 时区

  redis:
    host    : '127.0.0.1'
    port    : 6379
    db      : 0
    password: null

# 站点服务
webServer:
  host: 'localhost'
  port: 5080

  pageSize: 20
  pageSizeMax: 1000

  logLevel: 'ERROR' # 日志等级（ALL, TRACE, DEBUG, INFO, WARN, ERROR, FATAL, MARK, OFF）

  xAuthMaxAge: 7200           # 用户认证通用过期时间，秒
  xAuthHeader: 'x-auth-token' # HTTP Header中用户令牌字段名，`false`为禁用
  xAuthQuery : 'xAuthToken'   # QueryString中用户令牌字段名，`false`为禁用
  xAuthCookie: 'xAuthToken'   # Cookie中用户令牌字段名, `false`为禁用

  salt: 'bin-admin'

  corsWhiteList:
    - 'admin.helibin.com'
    - 'api.helibin.com'

# API服务
apiServer:
  prefix: '/v1'

# 公共API
openAPI:
  taobao:
    ip: 'http://ip.taobao.com/service/getIpInfo2.php?ip='

# hbs模板
hbs:
  partials:
    'header.base': 'layouts/header.base'
    'header'     : 'layouts/header'
    'footer.base': 'layouts/footer.base'
    'footer'     : 'layouts/footer'

# AES加密
AES:
  key: 'jKDUqUyRezqNyQaY5faKYsZHLADHmD9e'
  iv: 'dvjMpXLMb8592RZr'
